<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $startdate
     * @param $enddate
     * @return array
     */
    public function getByDateRange($startdate,$enddate){
        if($startdate != null && $enddate != null){
            return $this->createQueryBuilder('t')
                ->where('t.createdAt >= :startdate AND t.createdAt <= :enddate')
                ->setParameters([
                    "startdate" => $startdate,
                    "enddate" => $enddate
                ])
                ->getQuery()->getResult();
        }elseif($startdate == null && $enddate != null){
            return $this->createQueryBuilder('t')
                ->where('t.createdAt <= :enddate')
                ->setParameter("enddate" , $enddate)
                ->getQuery()->getResult();
        }elseif($startdate != null && $enddate == null){
            return $this->createQueryBuilder('t')
                ->where(" t.createdAt like'%$startdate%' ")
                ->getQuery()->getResult();
        }else{
            return $this->createQueryBuilder('t')
                ->select('t')
                ->getQuery()->getResult();
        }
    }
}
